send action metrics to s3
searchspring/snap-action pull request #25
Opened 2022-05-11 21:51 UTC by dkonieczek

2022-05-11 21:54 UTC, dkonieczek commented
Ready for review.
A run using this branch can be seen here: https://github.com/searchspring-implementations/stfrock.com.au/runs/6396473198?check_suite_focus=true

2022-05-11 23:05 UTC, korgon reviewed
I'd like to see an example of this logging a failure before approving.

2022-05-11 23:05 UTC, korgon commented on action.yml
> +    - run: date -u +"%FT%TZ" | tr -d '\n' > date.txt && npx -y jjo timestamp=@date.txt type=snap-action data=$(npx -y jjo repository=${{ steps.variables.outputs.repository }} conclusion=${{ github.ac
I'm guessing this falling outside of a named step with the `if` is what will cause this to run on both success and failure?

2022-05-12 14:23 UTC, korgon commented
Also - and this may be something to add down the road; it would be nice to know which step failed. For example, if the the authentication (siteId verification) failed, that failure step being a piece of the data could be nice to have available without having to dig into the action. Also, perhaps the action run #?

2022-05-12 22:56 UTC, korgon requested changes
This is looking pretty good.

This is a small thing, but if possible I'd like to see our data keys have some standard naming convention. We are using snake_case and camelCase - we should stick with one or the other. My preference would be camelCase for JSON data.

2022-05-12 22:56 UTC, korgon commented on action.yml
> +            durration=$(expr $(date -u +%s) - ${{ steps.variables.outputs.startTime }} ) \
Misspelling of duration?

2022-05-13 16:09 UTC, korgon approved these changes
This is going to provide some nice insight for us. Please squash and merge this branch (tons of commits) :)

2022-05-17 17:14 UTC, merged